# Generated by Django 3.2 on 2023-02-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDoList',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=None, max_length=200, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
